#!/usr/bin/env bash
# Production installer executed only from a verified release package.
# Interactive wizard + Docker Compose stack under /opt/ifilm.
set -euo pipefail

IFILM_HOME="${IFILM_HOME:-/opt/ifilm}"
IFILM_ETC="${IFILM_ETC:-/etc/ifilm}"
IFILM_VAR="${IFILM_VAR:-/var/lib/ifilm}"
IFILM_LOG="${IFILM_LOG:-/var/log/ifilm}"
ENV_FILE="${IFILM_ETC}/ifilm.env"
COMPOSE_FILE="${IFILM_HOME}/current/packaging/compose/docker-compose.production.yml"
NONINTERACTIVE="${IFILM_NONINTERACTIVE:-0}"

log() { printf '[ifilm] %s\n' "$*"; }
die() { printf '[ifilm] ERROR: %s\n' "$*" >&2; exit 1; }

rand_hex() { openssl rand -hex 32; }
rand_password() { openssl rand -base64 32 | tr -d '/+=' | head -c 40; }

prompt() {
  local var="$1" msg="$2" default="${3:-}"
  if [[ "$NONINTERACTIVE" == "1" ]]; then
    printf -v "$var" '%s' "${!var:-$default}"
    return
  fi
  local reply
  if [[ -n "$default" ]]; then
    read -r -p "${msg} [${default}]: " reply || true
    printf -v "$var" '%s' "${reply:-$default}"
  else
    read -r -p "${msg}: " reply || true
    printf -v "$var" '%s' "$reply"
  fi
}

prompt_secret() {
  local var="$1" msg="$2"
  if [[ "$NONINTERACTIVE" == "1" ]]; then
    [[ -n "${!var:-}" ]] || printf -v "$var" '%s' "$(rand_password)"
    return
  fi
  local reply
  read -r -s -p "${msg}: " reply || true
  echo
  if [[ -z "$reply" ]]; then
    reply="$(rand_password)"
    log "generated ${var}"
  fi
  printf -v "$var" '%s' "$reply"
}

create_dirs() {
  mkdir -p \
    "$IFILM_ETC" \
    "$IFILM_LOG" \
    "$IFILM_VAR/postgres" \
    "$IFILM_VAR/redis" \
    "$IFILM_VAR/media/originals" \
    "$IFILM_VAR/media/packages" \
    "$IFILM_VAR/media/temp" \
    "$IFILM_VAR/media/trailers" \
    "$IFILM_VAR/media/posters" \
    "$IFILM_VAR/media/backdrops" \
    "$IFILM_VAR/media/subtitles" \
    "$IFILM_VAR/artwork" \
    "$IFILM_VAR/backups" \
    "$IFILM_HOME/agent" \
    /run/ifilm
  chmod 755 "$IFILM_ETC" "$IFILM_VAR" "$IFILM_LOG"
}

wizard() {
  PUBLIC_DOMAIN="${PUBLIC_DOMAIN:-}"
  ADMIN_EMAIL="${ADMIN_EMAIL:-}"
  ADMIN_USERNAME="${ADMIN_USERNAME:-admin}"
  ADMIN_PASSWORD="${ADMIN_PASSWORD:-}"
  INSTALL_MODE="${INSTALL_MODE:-production}"
  HTTPS_MODE="${HTTPS_MODE:-disabled}"
  ENABLE_UPLOADS="${ENABLE_UPLOADS:-true}"

  prompt PUBLIC_DOMAIN "Public domain (e.g. ifilm.example.com)" "localhost"
  prompt ADMIN_EMAIL "Administrator email" "admin@${PUBLIC_DOMAIN}"
  prompt ADMIN_USERNAME "Administrator username" "admin"
  prompt_secret ADMIN_PASSWORD "Administrator password (empty = generate)"
  prompt INSTALL_MODE "Installation mode (staging|production)" "production"
  prompt HTTPS_MODE "HTTPS mode (disabled|provided)" "disabled"
  prompt ENABLE_UPLOADS "Enable uploads (true|false)" "true"

  case "$INSTALL_MODE" in
    staging|production) ;;
    *) die "INSTALL_MODE must be staging or production" ;;
  esac
  [[ "${#ADMIN_PASSWORD}" -ge 12 ]] || die "admin password must be at least 12 characters"
}

write_env() {
  local pg_pass redis_pass jwt playback agent
  pg_pass="$(rand_password)"
  redis_pass="$(rand_password)"
  jwt="$(rand_hex)"
  playback="$(rand_hex)"
  agent="$(rand_hex)"

  umask 077
  cat >"$ENV_FILE" <<EOF
# Generated by iFilm installer. Do not commit.
APP_ENV=${INSTALL_MODE}
DEBUG=false
PUBLIC_DOMAIN=${PUBLIC_DOMAIN}
CORS_ORIGINS=["https://${PUBLIC_DOMAIN}","http://${PUBLIC_DOMAIN}","http://localhost"]
CSP_MODE=production

POSTGRES_DB=ifilm
POSTGRES_USER=ifilm
POSTGRES_PASSWORD=${pg_pass}
POSTGRES_HOST=postgres
POSTGRES_PORT=5432

REDIS_HOST=redis
REDIS_PORT=6379
REDIS_DB=0
REDIS_PASSWORD=${redis_pass}
REDIS_REQUIRED=true

JWT_SECRET=${jwt}
PLAYBACK_TOKEN_SECRET=${playback}
UPDATE_AGENT_SHARED_SECRET=${agent}
UPDATE_AGENT_SOCKET=/run/ifilm/update-agent.sock
UPDATE_CHANNEL=stable

ADMIN_BOOTSTRAP_USERNAME=${ADMIN_USERNAME}
ADMIN_BOOTSTRAP_PASSWORD=${ADMIN_PASSWORD}
ADMIN_BOOTSTRAP_EMAIL=${ADMIN_EMAIL}

MEDIA_ROOT=/data/media
ARTWORK_ROOT=/data/artwork
HLS_PUBLIC_BASE_URL=https://${PUBLIC_DOMAIN}/api/stream

ENABLE_UPLOADS=${ENABLE_UPLOADS}
ENABLE_MEDIA_PROCESSING=true
ENABLE_HLS_ENCODING=true
ENABLE_LOCAL_STREAMING=true
ENABLE_WATCH_HISTORY=true
ENABLE_CDN_SYNC=false
ENABLE_ENCODING=false
ENABLE_RADIUS_LOGIN=false

SUBSCRIBER_IDENTITY_MODE=disabled
STAGING_ALLOW_FIXTURE_AUTH=false
RADIUS_ENTITLEMENT_MAPPING_ENABLED=false
RADIUS_ENABLED=false
RADIUS_MODE=live

IFILM_VERSION_FILE=/opt/ifilm/current/release-manifest.json
MAINTENANCE_MODE=false
EOF

  if [[ "$INSTALL_MODE" == "staging" ]]; then
    # Staging may later enable fixture via explicit operator edit; keep defaults safe.
    sed -i 's/^APP_ENV=.*/APP_ENV=staging/' "$ENV_FILE"
  fi

  chown root:root "$ENV_FILE"
  chmod 600 "$ENV_FILE"
  log "wrote ${ENV_FILE} (mode 600)"
}

install_agent_unit() {
  install -d -m 0755 /etc/systemd/system
  cat >/etc/systemd/system/ifilm-update-agent.service <<'UNIT'
[Unit]
Description=iFilm update agent (privileged, typed protocol)
After=network.target docker.service
Requires=docker.service

[Service]
Type=simple
User=root
Group=root
WorkingDirectory=/opt/ifilm/current
EnvironmentFile=/etc/ifilm/ifilm.env
ExecStart=/usr/bin/python3 /opt/ifilm/current/packaging/update-agent/agent.py
Restart=on-failure
RestartSec=3
NoNewPrivileges=true
ProtectSystem=strict
ReadWritePaths=/opt/ifilm /var/lib/ifilm /var/log/ifilm /etc/ifilm /run/ifilm /tmp
PrivateTmp=true

[Install]
WantedBy=multi-user.target
UNIT
  systemctl daemon-reload
  systemctl enable --now ifilm-update-agent.service
}

start_stack() {
  [[ -f "$COMPOSE_FILE" ]] || die "missing compose file ${COMPOSE_FILE}"
  docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" pull || true
  docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" up -d --build
  log "waiting for backend health"
  for _ in $(seq 1 60); do
    if curl -fsS "http://127.0.0.1:8080/api/health/live" >/dev/null 2>&1; then
      break
    fi
    sleep 2
  done
  curl -fsS "http://127.0.0.1:8080/api/health/ready" >/dev/null \
    || die "API readiness check failed"

  docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" exec -T backend-api \
    sh -c 'set -a; . /run/ifilm/runtime.env 2>/dev/null || true; set +a; alembic upgrade head'
  # Explicit admin bootstrap only — never create_all, never unsafe demo seed.
  docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" exec -T backend-api \
    sh -c 'set -a; . /run/ifilm/runtime.env 2>/dev/null || true; set +a; python -m scripts.seed_production_admin'
}

main() {
  [[ "$(id -u)" -eq 0 ]] || die "must run as root"
  create_dirs
  wizard
  write_env
  install_agent_unit
  start_stack
  log "installation complete"
  log "admin UI: http://${PUBLIC_DOMAIN}:8080/admin (or configured HTTPS endpoint)"
  log "secrets stored in ${ENV_FILE} (not printed)"
}

main "$@"
